import { test } from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { parse, visit } from 'graphql'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const projectRoot = path.resolve(__dirname, '..')

const SUPERGRAOH_PATH = path.join(projectRoot, 'supergraph.graphql')

const readSupergraph = async () => {
  return fs.readFile(SUPERGRAOH_PATH, 'utf-8')
}

const checkSupergraphExists = async () => {
  try {
    await fs.access(SUPERGRAOH_PATH)
    return true
  } catch {
    return false
  }
}

// ── Query field coverage ────────────────────────────────────────────

test('generated GraphQL Query surface remains stable', async (t) => {
  if (!(await checkSupergraphExists())) {
    t.skip('supergraph.graphql not found; run npm run build first')
    return
  }
  const sdl = await readSupergraph()
  const fields = new Set()

  visit(parse(sdl), {
    ObjectTypeDefinition(node) {
      if (node.name.value === 'Query') {
        for (const field of node.fields ?? []) {
          fields.add(field.name.value)
        }
      }
    },
  })

  const expected = [
    'character',
    'config',
    'episodes',
    'index',
    'news',
    'newsFeed',
    'person',
    'series',
    'studio',
    'vapid',
  ]

  for (const field of expected) {
    assert.ok(fields.has(field), `Expected Query.${field}`)
  }
})

// ── Forbidden generated type names: undefined check ─────────────────

test('generated GraphQL types do not contain undefined type name', async (t) => {
  if (!(await checkSupergraphExists())) {
    t.skip('supergraph.graphql not found; run npm run build first')
    return
  }
  const sdl = await readSupergraph()
  const offenders = []

  visit(parse(sdl), {
    ObjectTypeDefinition(node) {
      const name = node.name.value
      if (name === 'undefined') offenders.push(name)
    },
    InputObjectTypeDefinition(node) {
      const name = node.name.value
      if (name === 'undefined') offenders.push(name)
    },
  })

  assert.deepEqual(
    offenders,
    [],
    offenders.length > 0
      ? `Forbidden type names found: ${offenders.join(', ')}`
      : undefined,
  )
})

// ── Forbidden generated type names: full patterns ───────────────────
// Deferred until on-the-edge#379 lands and source normalizes inline schemas.
// Enabling this now would fail on ~27 query_-prefixed types generated by
// GraphQL Mesh from unnamed inline response schemas in the OpenAPI paths.
//
// test('generated GraphQL types do not contain path-derived / forbidden names', async () => {
//   const sdl = await readSupergraph()
//   const offenders = []
//
//   const isForbidden = (name) =>
//     /^query_/i.test(name) ||
//     /_items_/i.test(name) ||
//     /undefined/i.test(name) ||
//     /inline/i.test(name) ||
//     /response\d+$/i.test(name)
//
//   visit(parse(sdl), {
//     ObjectTypeDefinition(node) {
//       const name = node.name.value
//       if (isForbidden(name)) offenders.push(name)
//     },
//     InputObjectTypeDefinition(node) {
//       const name = node.name.value
//       if (isForbidden(name)) offenders.push(name)
//     },
//   })
//
//   assert.deepEqual(offenders, [])
// })
